### ISSUE TITLE
get_block_size crashes on aufs

### ISSUE THREAD

**Issue by kad** [01org/bmap-tools#15]
easily reproducible in docker container (not over btrfs or lvm storage drivers)
```
./bmaptool create /tmp/test.img
Traceback (most recent call last):
  File "./bmaptool", line 744, in <module>
    sys.exit(main())
  File "./bmaptool", line 728, in main
    args.func(args, log)
  File "./bmaptool", line 558, in create_command
    creator = BmapCreate.BmapCreate(args.image, output, "sha256", log)
  File "/home/kad/git/bmap-tools/bmaptools/BmapCreate.py", line 175, in __init__
    self.filemap = Filemap.filemap(self._f_image, self._log)
  File "/home/kad/git/bmap-tools/bmaptools/Filemap.py", line 518, in filemap
    return FilemapFiemap(image, log)
  File "/home/kad/git/bmap-tools/bmaptools/Filemap.py", line 335, in __init__
    _FilemapBase.__init__(self, image, log)
  File "/home/kad/git/bmap-tools/bmaptools/Filemap.py", line 86, in __init__
    self.blocks_cnt /= self.block_size
ZeroDivisionError: integer division or modulo by zero
```

**Comment by dedekind** [comment]
Nice catch. Are you testing this on every file-system?

**Comment by kad** [comment]
no, it was reported as part of testing under docker, where people are using default "dumb" storage to put build results.
